/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerLoginRouteImport } from './routes/volunteer-login'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer-dashboard'
import { Route as RegisterVolunteerRouteImport } from './routes/register-volunteer'
import { Route as RegisterLearnerRouteImport } from './routes/register-learner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as LearnerDashboardRouteImport } from './routes/learner-dashboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelplineRouteImport } from './routes/helpline'
import { Route as GroupChatRouteImport } from './routes/group-chat'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CommunityMeetingsRouteImport } from './routes/community-meetings'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingSignupIdRouteImport } from './routes/meeting-signup.$id'

const VolunteerLoginRoute = VolunteerLoginRouteImport.update({
  id: '/volunteer-login',
  path: '/volunteer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/volunteer-dashboard',
  path: '/volunteer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterVolunteerRoute = RegisterVolunteerRouteImport.update({
  id: '/register-volunteer',
  path: '/register-volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterLearnerRoute = RegisterLearnerRouteImport.update({
  id: '/register-learner',
  path: '/register-learner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: '/learner-dashboard',
  path: '/learner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplineRoute = HelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupChatRoute = GroupChatRouteImport.update({
  id: '/group-chat',
  path: '/group-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMeetingsRoute = CommunityMeetingsRouteImport.update({
  id: '/community-meetings',
  path: '/community-meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingSignupIdRoute = MeetingSignupIdRouteImport.update({
  id: '/meeting-signup/$id',
  path: '/meeting-signup/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/badges': typeof BadgesRoute
  '/bookmarks': typeof BookmarksRoute
  '/community-meetings': typeof CommunityMeetingsRoute
  '/feedback': typeof FeedbackRoute
  '/group-chat': typeof GroupChatRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/learner-dashboard': typeof LearnerDashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-learner': typeof RegisterLearnerRoute
  '/register-volunteer': typeof RegisterVolunteerRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/volunteer-login': typeof VolunteerLoginRoute
  '/meeting-signup/$id': typeof MeetingSignupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/badges': typeof BadgesRoute
  '/bookmarks': typeof BookmarksRoute
  '/community-meetings': typeof CommunityMeetingsRoute
  '/feedback': typeof FeedbackRoute
  '/group-chat': typeof GroupChatRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/learner-dashboard': typeof LearnerDashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-learner': typeof RegisterLearnerRoute
  '/register-volunteer': typeof RegisterVolunteerRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/volunteer-login': typeof VolunteerLoginRoute
  '/meeting-signup/$id': typeof MeetingSignupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/badges': typeof BadgesRoute
  '/bookmarks': typeof BookmarksRoute
  '/community-meetings': typeof CommunityMeetingsRoute
  '/feedback': typeof FeedbackRoute
  '/group-chat': typeof GroupChatRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/learner-dashboard': typeof LearnerDashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-learner': typeof RegisterLearnerRoute
  '/register-volunteer': typeof RegisterVolunteerRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/volunteer-login': typeof VolunteerLoginRoute
  '/meeting-signup/$id': typeof MeetingSignupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/badges'
    | '/bookmarks'
    | '/community-meetings'
    | '/feedback'
    | '/group-chat'
    | '/helpline'
    | '/home'
    | '/learner-dashboard'
    | '/learning-paths'
    | '/lessons'
    | '/login'
    | '/register'
    | '/register-learner'
    | '/register-volunteer'
    | '/volunteer-dashboard'
    | '/volunteer-login'
    | '/meeting-signup/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/badges'
    | '/bookmarks'
    | '/community-meetings'
    | '/feedback'
    | '/group-chat'
    | '/helpline'
    | '/home'
    | '/learner-dashboard'
    | '/learning-paths'
    | '/lessons'
    | '/login'
    | '/register'
    | '/register-learner'
    | '/register-volunteer'
    | '/volunteer-dashboard'
    | '/volunteer-login'
    | '/meeting-signup/$id'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/badges'
    | '/bookmarks'
    | '/community-meetings'
    | '/feedback'
    | '/group-chat'
    | '/helpline'
    | '/home'
    | '/learner-dashboard'
    | '/learning-paths'
    | '/lessons'
    | '/login'
    | '/register'
    | '/register-learner'
    | '/register-volunteer'
    | '/volunteer-dashboard'
    | '/volunteer-login'
    | '/meeting-signup/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BadgesRoute: typeof BadgesRoute
  BookmarksRoute: typeof BookmarksRoute
  CommunityMeetingsRoute: typeof CommunityMeetingsRoute
  FeedbackRoute: typeof FeedbackRoute
  GroupChatRoute: typeof GroupChatRoute
  HelplineRoute: typeof HelplineRoute
  HomeRoute: typeof HomeRoute
  LearnerDashboardRoute: typeof LearnerDashboardRoute
  LearningPathsRoute: typeof LearningPathsRoute
  LessonsRoute: typeof LessonsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterLearnerRoute: typeof RegisterLearnerRoute
  RegisterVolunteerRoute: typeof RegisterVolunteerRoute
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  VolunteerLoginRoute: typeof VolunteerLoginRoute
  MeetingSignupIdRoute: typeof MeetingSignupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer-login': {
      id: '/volunteer-login'
      path: '/volunteer-login'
      fullPath: '/volunteer-login'
      preLoaderRoute: typeof VolunteerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-dashboard': {
      id: '/volunteer-dashboard'
      path: '/volunteer-dashboard'
      fullPath: '/volunteer-dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-volunteer': {
      id: '/register-volunteer'
      path: '/register-volunteer'
      fullPath: '/register-volunteer'
      preLoaderRoute: typeof RegisterVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-learner': {
      id: '/register-learner'
      path: '/register-learner'
      fullPath: '/register-learner'
      preLoaderRoute: typeof RegisterLearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner-dashboard': {
      id: '/learner-dashboard'
      path: '/learner-dashboard'
      fullPath: '/learner-dashboard'
      preLoaderRoute: typeof LearnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpline': {
      id: '/helpline'
      path: '/helpline'
      fullPath: '/helpline'
      preLoaderRoute: typeof HelplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-chat': {
      id: '/group-chat'
      path: '/group-chat'
      fullPath: '/group-chat'
      preLoaderRoute: typeof GroupChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-meetings': {
      id: '/community-meetings'
      path: '/community-meetings'
      fullPath: '/community-meetings'
      preLoaderRoute: typeof CommunityMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-signup/$id': {
      id: '/meeting-signup/$id'
      path: '/meeting-signup/$id'
      fullPath: '/meeting-signup/$id'
      preLoaderRoute: typeof MeetingSignupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BadgesRoute: BadgesRoute,
  BookmarksRoute: BookmarksRoute,
  CommunityMeetingsRoute: CommunityMeetingsRoute,
  FeedbackRoute: FeedbackRoute,
  GroupChatRoute: GroupChatRoute,
  HelplineRoute: HelplineRoute,
  HomeRoute: HomeRoute,
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearningPathsRoute: LearningPathsRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterLearnerRoute: RegisterLearnerRoute,
  RegisterVolunteerRoute: RegisterVolunteerRoute,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  VolunteerLoginRoute: VolunteerLoginRoute,
  MeetingSignupIdRoute: MeetingSignupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
