/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterVolunteerRouteImport } from './routes/register-volunteer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelplineRouteImport } from './routes/helpline'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as IndexRouteImport } from './routes/index'

const RegisterVolunteerRoute = RegisterVolunteerRouteImport.update({
  id: '/register-volunteer',
  path: '/register-volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplineRoute = HelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/learning-paths': typeof LearningPathsRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/register-volunteer': typeof RegisterVolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/learning-paths': typeof LearningPathsRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/register-volunteer': typeof RegisterVolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/learning-paths': typeof LearningPathsRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/register-volunteer': typeof RegisterVolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/helpline'
    | '/home'
    | '/learning-paths'
    | '/lessons'
    | '/login'
    | '/register-volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedback'
    | '/helpline'
    | '/home'
    | '/learning-paths'
    | '/lessons'
    | '/login'
    | '/register-volunteer'
  id:
    | '__root__'
    | '/'
    | '/feedback'
    | '/helpline'
    | '/home'
    | '/learning-paths'
    | '/lessons'
    | '/login'
    | '/register-volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbackRoute: typeof FeedbackRoute
  HelplineRoute: typeof HelplineRoute
  HomeRoute: typeof HomeRoute
  LearningPathsRoute: typeof LearningPathsRoute
  LessonsRoute: typeof LessonsRoute
  LoginRoute: typeof LoginRoute
  RegisterVolunteerRoute: typeof RegisterVolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-volunteer': {
      id: '/register-volunteer'
      path: '/register-volunteer'
      fullPath: '/register-volunteer'
      preLoaderRoute: typeof RegisterVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpline': {
      id: '/helpline'
      path: '/helpline'
      fullPath: '/helpline'
      preLoaderRoute: typeof HelplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbackRoute: FeedbackRoute,
  HelplineRoute: HelplineRoute,
  HomeRoute: HomeRoute,
  LearningPathsRoute: LearningPathsRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  RegisterVolunteerRoute: RegisterVolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
